# Generated by Django 2.2.3 on 2019-07-23 15:40

from django.db import migrations, models
import oidc_provider.models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0026_client_multiple_response_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='auth_type',
            field=models.CharField(blank=True, choices=[('client_secret_basic', 'Client Secret Basic'), ('client_secret_post', 'Client Secret Post'), ('client_secret_jwt', 'Client Secret JWT'), ('private_key_jwt', 'Private Key JWT'), (oidc_provider.models.AuthMethods('none'), 'None')], default=oidc_provider.models.AuthMethods('client_secret_basic'), help_text='Client Authentication Type (<a href="https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication">Info</a>)', max_length=30, verbose_name='Client Auth Type'),
        ),
        migrations.AddField(
            model_name='client',
            name='public_key',
            field=models.TextField(blank=True, default='', help_text='Client public key (PEM format). Used for decrypting JWTs for Private Key JWT Auth', verbose_name='Public Key'),
        ),
        migrations.AddField(
            model_name='client',
            name='public_key_url',
            field=models.URLField(blank=True, default='', help_text='URL of public keyset if available', verbose_name='Public Keyset URL'),
        ),
    ]
