# Generated by Django 2.2.3 on 2019-07-22 19:16

from django.db import migrations, models
import oidc_provider.models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0026_client_multiple_response_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='auth_type',
            field=models.CharField(blank=True, choices=[(oidc_provider.models.AuthMethods('client_secret_basic'), 'Client Secret Basic'), (oidc_provider.models.AuthMethods('client_secret_post'), 'Client Secret Post'), (oidc_provider.models.AuthMethods('client_secret_jwt'), 'Client Secret JWT'), (oidc_provider.models.AuthMethods('private_key_jwt'), 'Private Key JWT'), (oidc_provider.models.AuthMethods('none'), 'None')], default=oidc_provider.models.AuthMethods('client_secret_basic'), help_text='', max_length=30, verbose_name='Client Auth Type'),
        ),
        migrations.AddField(
            model_name='client',
            name='public_key',
            field=models.TextField(blank=True, default='', help_text='Client public key, used for decrypting JWTs', verbose_name='Public Key'),
        ),
    ]
