# Generated by Django 2.2.3 on 2019-07-23 16:25

from django.db import migrations, models
import oidc_provider.models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0027_auto_20190723_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='auth_type',
            field=models.CharField(blank=True, choices=[('client_secret_basic', 'Client Secret Basic'), ('client_secret_post', 'Client Secret Post'), ('client_secret_jwt', 'Client Secret JWT'), ('private_key_jwt', 'Private Key JWT'), (oidc_provider.models.AuthMethods('none'), 'None')], default='client_secret_basic', help_text='Client Authentication Type (<a href="https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication">Info</a>)', max_length=30, verbose_name='Client Auth Type'),
        ),
    ]
