# Generated by Django 2.2.3 on 2019-07-22 21:19

from django.db import migrations, models
import oidc_provider.models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0027_auto_20190722_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='public_key_url',
            field=models.URLField(blank=True, default='', help_text='URL of public keyset if available', verbose_name='Public Keyset URL'),
        ),
        migrations.AlterField(
            model_name='client',
            name='auth_type',
            field=models.CharField(blank=True, choices=[('client_secret_basic', 'Client Secret Basic'), ('client_secret_post', 'Client Secret Post'), ('client_secret_jwt', 'Client Secret JWT'), ('private_key_jwt', 'Private Key JWT'), (oidc_provider.models.AuthMethods('none'), 'None')], default=oidc_provider.models.AuthMethods('client_secret_basic'), help_text='', max_length=30, verbose_name='Client Auth Type'),
        ),
    ]
